version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: excelai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: excel_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: excelai_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
